version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379