// Code generated by hertz generator.

package token

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revoketokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifytokenMw() []app.HandlerFunc {
	// your code...
	return nil
}
