// Code generated by Kitex v0.9.1. DO NOT EDIT.

package authservice

import (
	"context"
	auth "github.com/beatpika/eshop/rpc_gen/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateToken(ctx context.Context, Req *auth.GenerateTokenRequest, callOptions ...callopt.Option) (r *auth.GenerateTokenResponse, err error)
	VerifyToken(ctx context.Context, Req *auth.VerifyTokenRequest, callOptions ...callopt.Option) (r *auth.VerifyTokenResponse, err error)
	RefreshToken(ctx context.Context, Req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.RefreshTokenResponse, err error)
	RevokeToken(ctx context.Context, Req *auth.RevokeTokenRequest, callOptions ...callopt.Option) (r *auth.RevokeTokenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) GenerateToken(ctx context.Context, Req *auth.GenerateTokenRequest, callOptions ...callopt.Option) (r *auth.GenerateTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateToken(ctx, Req)
}

func (p *kAuthServiceClient) VerifyToken(ctx context.Context, Req *auth.VerifyTokenRequest, callOptions ...callopt.Option) (r *auth.VerifyTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyToken(ctx, Req)
}

func (p *kAuthServiceClient) RefreshToken(ctx context.Context, Req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.RefreshTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, Req)
}

func (p *kAuthServiceClient) RevokeToken(ctx context.Context, Req *auth.RevokeTokenRequest, callOptions ...callopt.Option) (r *auth.RevokeTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeToken(ctx, Req)
}
