// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	token "github.com/beatpika/eshop/app/api/biz/router/token"
	user "github.com/beatpika/eshop/app/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	token.Register(r)

	user.Register(r)
}
