// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategorytreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductsbycategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _product_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _skuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sku_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateskustockMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteskuMw() []app.HandlerFunc {
	// your code...
	return nil
}
